services:
    web:
        build: .
        ports:
            - 3000:3000
        image: shadow783/rag-frontend:1.1
        container_name: openai-RAG-frontend
        environment:
            - BACKEND_URL=http://localhost:8000
