services:
    backend:
        build:
            context: ./Backend
            dockerfile: Dockerfile
        ports:
            - 5400:5400
        image: sahasoumadip/openai-rag:1.3.1
        container_name: RAG_Backend
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - LLM_MODEL_NAME=${LLM_MODEL_NAME}
            - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
            - VECTORDB_HOST=${VECTORDB_HOST}
            - VECTORDB_INDEX=${VECTORDB_INDEX}
            - VECTORDB_USER_NAME=${VECTORDB_USER_NAME}
            - VECTORDB_PASSWORD=${VECTORDB_PASSWORD}
        command: "--workers 2"
        networks:
            - openai-rag

    frontend:
        # build:
        #     context: ./Frontend
        #     dockerfile: Dockerfile
        ports:
            - 3000:3000
        environment:
            - BACKEND_URL=http://localhost:5400
        image: shadow783/rag-frontend:1.1
        container_name: RAG-Frontend
        networks:
            - openai-rag

networks:
    openai-rag:
        driver: bridge
        name: openai-rag
