services:
    backend:
        # build:
        #     context: ./Backend
        #     dockerfile: Dockerfile
        ports:
            - 5400:5400
        image: sahasoumadip/openai-rag:1.3
        container_name: RAG_Backend
        environment:
            - OPENAI_API_KEY
            - llm_model_name
            - embedding_model_name
            - VectorDB_HOST
            - VectorDB_INDEX
            - VectorDB_USER_NAME
            - VectorDB_password
        command: "--workers 2"
        networks:
            - openai-rag

    frontend:
        # build:
        #     context: ./Frontend
        #     dockerfile: Dockerfile
        #     args:
        #         - SERVER_URL=http://localhost:5400
        ports:
            - 3000:3000
        image: shadow783/rag-frontend:1.0
        container_name: rag-frontend
        networks:
            - openai-rag

networks:
    openai-rag:
        driver: bridge
        name: openai-rag
