version: '3.8'
services:
  openai-rag:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5400:5400
    image: sahasoumadip/openai-rag:1.3.1
    container_name: RAG_Backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL_NAME=${LLM_MODEL_NAME}
      - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
      - VECTORDB_HOST=${VECTORDB_HOST}
      - VECTORDB_INDEX=${VECTORDB_INDEX}
      - VECTORDB_USER_NAME=${VECTORDB_USER_NAME}
      - VECTORDB_PASSWORD=${VECTORDB_PASSWORD}
    command: --workers 2
    # restart: always
